### ISSUE TITLE
Crash on nexus 5x

### ISSUE THREAD

**Issue by YuckFo** [xenione/loupe#3]
Hi, 
I got crash on nexus 5x  android 7.1. any ideas?
`
java.lang.RuntimeException: Unable to start activity ComponentInfo{packagename.activity.Zoom}: android.view.InflateException: Binary XML file line #14: Binary XML file line #14: Error inflating class com.xenione.widget.loupe.LoupeView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: android.view.InflateException: Binary XML file line #14: Binary XML file line #14: Error inflating class com.xenione.widget.loupe.LoupeView
Caused by: android.view.InflateException: Binary XML file line #14: Error inflating class com.xenione.widget.loupe.LoupeView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
	at cz.davidmarak.lock100.activities.lockActivities.Zoom.onCreate(Zoom.java:25)
	at android.app.Activity.performCreate(Activity.java:6679)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.RectF.set(android.graphics.Rect)' on a null object reference
	at com.xenione.widget.loupe.LoupeView.invalidateDrawable(LoupeView.java:130)
	at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:435)
	at android.graphics.drawable.Drawable.setVisible(Drawable.java:819)
	at android.widget.ImageView.updateDrawable(ImageView.java:960)
	at android.widget.ImageView.setImageDrawable(ImageView.java:526)
	at android.widget.ImageView.<init>(ImageView.java:164)
	at android.widget.ImageView.<init>(ImageView.java:150)
	at android.widget.ImageView.<init>(ImageView.java:146)
	at com.xenione.widget.loupe.LoupeView.<init>(LoupeView.java:65)
	... 23 more`

**Comment by xenione** [comment]
Have you got that crash on the demo project? or on your own project?
Binary XML file line #14: Binary XML file line #14: Error inflating class  -> this is an Empty line.
